# Generated by Django 4.1.7 on 2023-04-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='用户地址'),
            preserve_default=False,
        ),
    ]
