# Generated by Django 4.1.7 on 2023-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0002_userinfomodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='address',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
    ]
