# Generated by Django 4.1.7 on 2023-04-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0003_userinfomodel_phone_alter_userinfomodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='number',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='number',
        ),
    ]
