# Generated by Django 4.2.5 on 2023-09-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0004_remove_carmodel_number_remove_ordermodel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.itemmodel', verbose_name='所属商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
                'db_table': 'db_comment',
            },
        ),
    ]
