# Generated by Django 4.2.5 on 2023-09-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0005_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='content',
            field=models.TextField(default='', verbose_name='评论内容'),
            preserve_default=False,
        ),
    ]
