# Generated by Django 4.2.1 on 2025-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0006_commentmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=3, verbose_name='尺寸'),
        ),
    ]
