# Generated by Django 4.2.1 on 2025-01-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0007_itemmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='size',
            field=models.CharField(default='M', max_length=3, verbose_name='尺寸'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='size',
            field=models.CharField(default='M', max_length=3, verbose_name='尺寸'),
        ),
    ]
