# Generated by Django 4.2.1 on 2025-01-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0009_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='快递单号'),
        ),
    ]
