# Generated by Django 4.2.1 on 2025-01-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0010_ordermodel_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=300, upload_to='item_images/', verbose_name='附加图片')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='图片描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_manage.itemmodel', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品附加图片',
                'verbose_name_plural': '商品附加图片',
                'db_table': 'db_item_image',
            },
        ),
    ]
