# Generated by Django 4.2.1 on 2025-01-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manage', '0011_itemimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('ordered', '已下单'), ('prepare', '备货中'), ('unshipped', '待发货'), ('shipped', '已发货'), ('completed', '已完成')], default='ordered', max_length=20, verbose_name='订单状态'),
        ),
    ]
